import { firestore } from "firebase-admin";

export const PRICES = [0.8, 0.9, 1.0, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5];
export const MERGE_PAYLOAD: firestore.SetOptions = { merge: true };
export const FILE_NAMES = { WEIGHTS: "tradePredictorWeights.json" };

export const PERIODS = {
  RSI: 14,
  SMA_SHORT: 7,
  SMA_MEDIUM: 20,
  SMA_LONG: 21,
  EMA_SHORT: 12,
  EMA_LONG: 26,
  MACD_SIGNAL: 9,
  BOLLINGER: 20,
  ATR: 14,
  VWAP: 7,
  STOCH_RSI: 14,
  STOCH_SMOOTH: 3,
  FIBONACCI: 30,
  VOL_SMA_SHORT: 5,
  VOL_SMA_LONG: 14,
  MOMENTUM: 10,
  ATR_BREAKOUT: 14,
  SMA_50: 50,
  SMA_200: 200,
  ADX: 14,
} as const;

export const STRATEGY_CONFIG = {
  MIN_CONFIDENCE_DEFAULT: 0.15, // Reasonable threshold for quality trades
  PROFIT_TAKE_MULTIPLIER_DEFAULT: 2.0,
  BASE_POSITION_SIZE_DEFAULT: 0.085,
  SLIPPAGE: 0.001,
  COMMISSION: 0.005,
  STOP_LOSS_MULTIPLIER_DEFAULT: 5.2,
  TRAILING_STOP_DEFAULT: 0.12,
  MIN_HOLD_DAYS_DEFAULT: 2.5,
  BUY_PROB_THRESHOLD_DEFAULT: 0.105,
  SELL_PROB_THRESHOLD_DEFAULT: 0.185,
  MOMENTUM_WINDOW_THRESHOLD: 0.01,
  MAX_ATR_THRESHOLD: 2.0, // Increased from 0.15 to allow more trades
  MIN_PROFIT_THRESHOLD: 0.0012,
  MOMENTUM_THRESHOLD: 0.0016,
  VOLATILITY_ADJUSTED_MOMENTUM_THRESHOLD: 0.016,
  TREND_STRENGTH_THRESHOLD: 0.0035,
  TREND_SLOPE_THRESHOLD: 0.0035,
  SHORT_MOMENTUM_THRESHOLD: 0.0035,
  DAYS_SINCE_TRADE_THRESHOLD: 5,
  DYNAMIC_BREAKOUT_THRESHOLD: 0.2,
  HIGH_CONFIDENCE_THRESHOLD: 0.46,
  MOMENTUM_MULTIPLIER: 0.05,
  MAX_PROFIT_TAKE: 2.0,
  NEGATIVE_MOMENTUM_THRESHOLD: -0.032,
  NEGATIVE_SHORT_MOMENTUM_THRESHOLD: -0.011,
  MEAN_REVERSION_THRESHOLD: 0.012,
  NEGATIVE_SHORT_MOMENTUM_MIN: -0.0085,
  MOMENTUM_MAX: 0.021,
  POSITION_SIZE_MAX: 0.3,
  POSITION_SIZE_MAX_HIGH_ATR: 0.35,
  POSITION_SIZE_MAX_HIGH_CONFIDENCE: 0.4,
  CONFIDENCE_BOOST_MULTIPLIER: 1.75,
  TREND_SLOPE_BOOST_THRESHOLD: 0.016,
  TREND_SLOPE_POSITION_BOOST: 1.28,
  VOLUME_BOOST_THRESHOLD: 1.2,
  NEGATIVE_DEVIATION_THRESHOLD: -0.015,
  VOLUME_MULTIPLIER: 1.5,
  TREND_STRENGTH_REVERSAL_THRESHOLD: -0.01,
  ATR_POSITION_THRESHOLD: 0.05,
  BUY_PROB_MAX_MULTIPLIER: 2.0,
  CONSECUTIVE_BUYS_MAX: 4,
  CONSECUTIVE_BUY_CONFIDENCE_LEVELS: [0.25, 0.3, 0.35, 0.4],
};

const MODEL_CONFIG_BASE = {
  CONV1D_FILTERS_1: 12, // Increased from 8 for better feature extraction
  CONV1D_FILTERS_2: 24, // Increased from 16 for better feature extraction
  CONV1D_KERNEL_SIZE_1: 5,
  CONV1D_KERNEL_SIZE_2: 3,
  LSTM_UNITS_1: 48, // Increased from 32 for better temporal modeling
  LSTM_UNITS_2: 24, // Increased from 16 for better temporal modeling
  LSTM_UNITS_3: 12, // Increased from 8 for better temporal modeling
  TIME_DISTRIBUTED_DENSE_UNITS: 16, // Increased from 12 for better feature learning
  DENSE_UNITS_1: 24, // Increased from 16 for better feature learning
  OUTPUT_UNITS: 2,
  L2_REGULARIZATION: 0.008, // Reduced from 0.01 for better generalization
  DROPOUT_RATE: 0.35, // Reduced from 0.4 for better training stability
  ATTENTION_UNITS_1: 16, // New: units for first attention layer
  ATTENTION_UNITS_2: 12, // New: units for second attention layer
  RESIDUAL_FILTERS: 8, // New: filters for residual connections
  TIMESTEPS_AFTER_CONV: 24,
  TIMESTEPS: 30,
  BTC_FEATURE_COUNT: 62, // Bitcoin features only
  FEATURE_COUNT: 62, // Total features
};

export const MODEL_CONFIG = {
  ...MODEL_CONFIG_BASE,
  LSTM1_INPUT_FEATURES: MODEL_CONFIG_BASE.CONV1D_FILTERS_2,
  CONV1D_1_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.CONV1D_KERNEL_SIZE_1,
    MODEL_CONFIG_BASE.FEATURE_COUNT,
    MODEL_CONFIG_BASE.CONV1D_FILTERS_1,
  ] as [number, number, number],
  CONV1D_2_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.CONV1D_KERNEL_SIZE_2,
    MODEL_CONFIG_BASE.CONV1D_FILTERS_1,
    MODEL_CONFIG_BASE.CONV1D_FILTERS_2,
  ] as [number, number, number],
  LSTM1_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.CONV1D_FILTERS_2,
    MODEL_CONFIG_BASE.LSTM_UNITS_1 * 4,
  ] as [number, number],
  LSTM1_RECURRENT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_1,
    MODEL_CONFIG_BASE.LSTM_UNITS_1 * 4,
  ] as [number, number],
  LSTM2_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_1,
    MODEL_CONFIG_BASE.LSTM_UNITS_2 * 4,
  ] as [number, number],
  LSTM2_RECURRENT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_2,
    MODEL_CONFIG_BASE.LSTM_UNITS_2 * 4,
  ] as [number, number],
  LSTM3_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_2,
    MODEL_CONFIG_BASE.LSTM_UNITS_3 * 4,
  ] as [number, number],
  LSTM3_RECURRENT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_3,
    MODEL_CONFIG_BASE.LSTM_UNITS_3 * 4,
  ] as [number, number],
  TIME_DISTRIBUTED_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_3,
    MODEL_CONFIG_BASE.TIME_DISTRIBUTED_DENSE_UNITS,
  ] as [number, number],
  DENSE_1_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.LSTM_UNITS_3,
    MODEL_CONFIG_BASE.DENSE_UNITS_1,
  ] as [number, number],
  DENSE_2_WEIGHT_SHAPE: [
    MODEL_CONFIG_BASE.DENSE_UNITS_1,
    Math.floor(MODEL_CONFIG_BASE.DENSE_UNITS_1 / 2),
  ] as [number, number],
  OUTPUT_WEIGHT_SHAPE: [
    Math.floor(MODEL_CONFIG_BASE.DENSE_UNITS_1 / 2),
    MODEL_CONFIG_BASE.OUTPUT_UNITS,
  ] as [number, number],
};

export const TRAINING_CONFIG = {
  EPOCHS: 120,
  BATCH_SIZE: 32,
  SHUFFLE_CHUNK_SIZE: 10,
  INITIAL_LEARNING_RATE: 0.001, // Standard learning rate
  MIN_LEARNING_RATE: 0.00001,
  CYCLIC_LR_STEP_SIZE: 12,
  OUTPUT_CLASSES: 2,
  START_DAYS_AGO: 1200,
  TRAIN_SPLIT: 0.8, // Standard split
  PREFETCH_BUFFER: 4,
  PATIENCE: 20, // Standard patience
  BYTES_TO_MB: 1024 * 1024,
  MS_TO_SECONDS: 1000,
  GAMMA: 0, // Disable focal loss - use standard cross-entropy
  ALPHA: [0.5, 0.5] as [number, number], // Balanced weights
  GRADIENT_CLIP_NORM: 1.0,
  LR_DECAY_RATE: 0.95, // Standard decay
  WARMUP_EPOCHS: 5,
  WARMUP_INITIAL_LR: 0.0001,
  ATTENTION_DROPOUT: 0.1,
  RESIDUAL_DROPOUT: 0.15,
  LAYER_NORM_EPSILON: 1e-6,
};

export const TIME_CONVERSIONS = {
  ONE_SECOND_IN_MILLISECONDS: 1000,
  THIRTY_MINUTES_IN_MILLISECONDS: 1800000,
  ONE_MINUTE_IN_SECONDS: 60,
  ONE_HOUR_IN_SECONDS: 3600,
  ONE_DAY_IN_MILLISECONDS: 86400000,
  ONE_DAY_IN_SECONDS: 86400,
  TIMESTEP_IN_SECONDS: MODEL_CONFIG_BASE.TIMESTEPS * 86400,
  ONE_MONTH_IN_DAYS: 30,
};
